import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'zh-CN',
  title: 'Nursing Documents',
  description: '养老护理项目开发文档站点',
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: '首页', link: '/' },
      { text: '文档索引', link: '/doc-index' },
      { text: '需求模块', link: '/requirements/project-overview' },
      { text: '架构设计', link: '/architecture/system-overview' },
      { text: '平台专题', link: '/platform/overview' },
      { text: '运行手册', link: '/operations/release-runbook' },
      { text: '模板', link: '/templates' },
    ],
    sidebar: [
      {
        text: '总览',
        items: [
          { text: '文档首页', link: '/' },
          { text: '文档索引', link: '/doc-index' },
          { text: '模板说明', link: '/templates' },
        ],
      },
      {
        text: '需求',
        items: [
          { text: '项目概览', link: '/requirements/project-overview' },
          { text: '长者管理', link: '/requirements/elderly-management' },
          { text: '健康监测', link: '/requirements/health-monitoring' },
          { text: '报警与事件', link: '/requirements/alerts-incidents' },
          { text: '员工协同', link: '/requirements/staff-collaboration' },
          { text: '机构管理', link: '/requirements/organization-management' },
          { text: '房间与床位', link: '/requirements/room-management' },
          { text: '设备管理', link: '/requirements/equipment-management' },
          { text: '物资管理', link: '/requirements/supply-management' },
          { text: 'AI 运营中心', link: '/requirements/ai-operations-center' },
        ],
      },
      {
        text: '架构',
        items: [
          { text: '系统概览', link: '/architecture/system-overview' },
        ],
      },
      {
        text: '平台专题',
        items: [
          { text: '专题总览', link: '/platform/overview' },
          { text: '平台总体架构', link: '/platform/PLATFORM_ARCHITECTURE' },
          { text: '实施蓝图', link: '/platform/IMPLEMENTATION_BLUEPRINT' },
          { text: '模块与页面映射', link: '/platform/MODULE_PAGE_MAPPING' },
          { text: '数据库设计', link: '/platform/DATABASE_DESIGN' },
          { text: 'AI Agent 架构', link: '/platform/AI_AGENT_ARCHITECTURE' },
          { text: '产品设计', link: '/platform/PRODUCT_DESIGN' },
          { text: '设计系统', link: '/platform/DESIGN_SYSTEM' },
          { text: 'UI 设计规范', link: '/platform/UI-DESIGN-SPEC' },
          { text: 'Admin 初版设计归档', link: '/platform/admin-design-system-legacy' },
        ],
      },
      {
        text: 'API',
        items: [
          { text: '核心模块草案', link: '/api/core-modules' },
          { text: '长者管理 API', link: '/api/elderly-management' },
          { text: '健康监测 API', link: '/api/health-monitoring' },
          { text: '报警与事件 API', link: '/api/alerts-incidents' },
          { text: '员工协同 API', link: '/api/staff-collaboration' },
          { text: '机构管理 API', link: '/api/organization-management' },
          { text: '房间与床位 API', link: '/api/room-management' },
          { text: '设备管理 API', link: '/api/equipment-management' },
          { text: '物资管理 API', link: '/api/supply-management' },
          { text: 'AI 运营中心 API', link: '/api/ai-operations-center' },
          { text: '接口级：长者列表查询', link: '/api/endpoint-elderly-list' },
          { text: '接口级：长者详情查询', link: '/api/endpoint-elderly-detail' },
          { text: '接口级：健康监测列表', link: '/api/endpoint-health-monitoring-list' },
          { text: '接口级：事故详情查询', link: '/api/endpoint-incident-detail' },
          { text: '接口级：排班更新', link: '/api/endpoint-staff-schedule-update' },
          { text: '接口级：机构详情查询', link: '/api/endpoint-organization-detail' },
          { text: '接口级：床位分配摘要', link: '/api/endpoint-room-allocation-summary' },
          { text: '接口级：设备监控状态', link: '/api/endpoint-equipment-monitoring' },
          { text: '接口级：低库存摘要', link: '/api/endpoint-supply-low-stock-summary' },
          { text: '接口级：AI 日志查询', link: '/api/endpoint-ai-logs-query' },
          { text: '字段级：健康监测列表', link: '/api/field-health-monitoring-list' },
          { text: '字段级：AI 日志查询', link: '/api/field-ai-logs-query' },
          { text: '字段级：事故详情', link: '/api/field-incident-detail' },
          { text: '字段级：排班更新', link: '/api/field-staff-schedule-update' },
          { text: '字段级：设备监控状态', link: '/api/field-equipment-monitoring' },
          { text: '契约级：健康监测列表', link: '/api/contract-health-monitoring-list' },
          { text: '契约级：AI 日志查询', link: '/api/contract-ai-logs-query' },
          { text: '契约级：排班更新', link: '/api/contract-staff-schedule-update' },
          { text: '契约级：事故详情', link: '/api/contract-incident-detail' },
          { text: '契约级：机构详情', link: '/api/contract-organization-detail' },
          { text: '契约级：设备监控状态', link: '/api/contract-equipment-monitoring' },
          { text: '契约级：低库存摘要', link: '/api/contract-supply-low-stock-summary' },
          { text: '治理级：长者详情查询', link: '/api/governance-elderly-detail' },
          { text: '治理级：健康监测列表', link: '/api/governance-health-monitoring-list' },
          { text: '治理级：排班更新', link: '/api/governance-staff-schedule-update' },
          { text: '治理级：机构详情查询', link: '/api/governance-organization-detail' },
          { text: '治理级：床位分配摘要', link: '/api/governance-room-allocation-summary' },
          { text: '治理级：设备监控状态', link: '/api/governance-equipment-monitoring' },
          { text: '治理级：低库存摘要', link: '/api/governance-supply-low-stock-summary' },
          { text: '治理级：AI 日志查询', link: '/api/governance-ai-logs-query' },
        ],
      },
      {
        text: 'UI',
        items: [
          { text: '管理端页面说明', link: '/ui/admin-overview' },
          { text: '长者管理页面', link: '/ui/elderly-management' },
          { text: '健康监测页面', link: '/ui/health-monitoring' },
          { text: '报警与事件页面', link: '/ui/alerts-incidents' },
          { text: '员工协同页面', link: '/ui/staff-collaboration' },
          { text: '机构管理页面', link: '/ui/organization-management' },
          { text: '房间与床位页面', link: '/ui/room-management' },
          { text: '设备管理页面', link: '/ui/equipment-management' },
          { text: '物资管理页面', link: '/ui/supply-management' },
          { text: 'AI 运营中心页面', link: '/ui/ai-operations-center' },
          { text: '页面级：Dashboard 首页', link: '/ui/page-dashboard' },
          { text: '页面级：长者详情页', link: '/ui/page-elderly-detail' },
          { text: '页面级：健康监测页', link: '/ui/page-health-monitoring' },
          { text: '页面级：报警中心页', link: '/ui/page-alerts-center' },
          { text: '页面级：事故详情页', link: '/ui/page-incident-detail' },
          { text: '页面级：排班管理页', link: '/ui/page-staff-schedule' },
          { text: '页面级：机构列表页', link: '/ui/page-organizations-overview' },
          { text: '页面级：房间列表页', link: '/ui/page-rooms-overview' },
          { text: '页面级：设备详情页', link: '/ui/page-equipment-detail' },
          { text: '页面级：物资列表页', link: '/ui/page-supplies-overview' },
          { text: '页面级：AI 日志审计页', link: '/ui/page-ai-logs' },
          { text: '流程级：健康监测页', link: '/ui/flow-health-monitoring' },
          { text: '流程级：报警中心页', link: '/ui/flow-alerts-center' },
          { text: '流程级：排班管理页', link: '/ui/flow-staff-schedule' },
          { text: '流程级：设备详情页', link: '/ui/flow-equipment-detail' },
          { text: '流程级：AI 日志页', link: '/ui/flow-ai-logs' },
          { text: '验收级：健康监测页', link: '/ui/test-health-monitoring' },
          { text: '验收级：报警中心页', link: '/ui/test-alerts-center' },
          { text: '验收级：排班管理页', link: '/ui/test-staff-schedule' },
          { text: '验收级：设备详情页', link: '/ui/test-equipment-detail' },
          { text: '验收级：AI 日志页', link: '/ui/test-ai-logs' },
          { text: '验收级：Dashboard 首页', link: '/ui/test-dashboard' },
          { text: '验收级：长者详情页', link: '/ui/test-elderly-detail' },
          { text: '验收级：机构列表页', link: '/ui/test-organizations-overview' },
          { text: '验收级：房间列表页', link: '/ui/test-rooms-overview' },
          { text: '验收级：物资列表页', link: '/ui/test-supplies-overview' },
          { text: '实施级：Dashboard 首页', link: '/ui/implementation-dashboard' },
          { text: '实施级：长者详情页', link: '/ui/implementation-elderly-detail' },
          { text: '实施级：健康监测页', link: '/ui/implementation-health-monitoring' },
          { text: '实施级：报警中心页', link: '/ui/implementation-alerts-center' },
          { text: '实施级：设备详情页', link: '/ui/implementation-equipment-detail' },
          { text: '实施级：房间列表页', link: '/ui/implementation-rooms-overview' },
          { text: '实施级：物资列表页', link: '/ui/implementation-supplies-overview' },
          { text: '实施级：AI 日志审计页', link: '/ui/implementation-ai-logs' },
        ],
      },
      {
        text: '运维',
        items: [
          { text: '发布运行手册', link: '/operations/release-runbook' },
          { text: 'Backend Provider 与 Observability 配置', link: '/operations/backend-provider-callback-observability-configuration' },
          { text: 'Admin 历史任务日志', link: '/operations/admin-task-log' },
        ],
      },
      {
        text: '会议纪要',
        items: [
          { text: '项目启动记录', link: '/meeting-notes/2026-03-30-kickoff' },
        ],
      },
    ],
    socialLinks: [],
    outline: 'deep',
    docFooter: {
      prev: '上一页',
      next: '下一页',
    },
    search: {
      provider: 'local'
    },
    footer: {
      message: 'Internal project documentation',
      copyright: 'nursing-documents'
    }
  }
})
